### ISSUE TITLE
Crytoshib evaluation

### ISSUE THREAD

**Issue by korvasc** [ioncoincore/ion#16]

**Comment by korvasc** [comment]
Crytosib is a marketing agency focued on the cryptocurrency/blockchain space. After a preliminary evaluation, I believe they can help IONcore details attached
[Cryptoshib.docx](https://github.com/ioncoincore/ion/files/5531486/Cryptoshib.docx)
[The_Pluton_wp EXAMPLE.pdf](https://github.com/ioncoincore/ion/files/5531510/The_Pluton_wp.EXAMPLE.pdf)

**Comment by ckti** [comment]
This makes sense to me...looks good

**Comment by cryptolinux** [comment]
@korvasc crypthoshib already wrote few articles about ion which were published, I think it would be better to use those articles as example instead of some non ion relevant, here are some ion/ionomy relevant:

- https://coinhub.news/cs/article/ionomy-a-crypto-gaming-ecosystem-marketplace-wallet-3838-more
- https://thebitcoinnews.com/ionomy-a-crypto-gaming-ecosystem-marketplace-wallet-more/
- https://cryptopys.com/2020/02/24/ionomy-a-crypto-gaming-ecosystem-marketplace-wallet-more/
- https://article.wn.com/view/2020/02/24/IONOMY_A_Crypto_Gaming_Ecosystem_Marketplace_Wallet_More_7/
- https://coinspectator.com/news/1552194/ionomy-a-crypto-gaming-ecosystem-marketplace-wallet-more

There are also some documents in other languages which he sent me back then. It is important to say that cryptoshib could write and publish in several languages too.

**Comment by korvasc** [comment]
Evaluation Complete
